### ISSUE TITLE
Doesn't show list of autocompletes, but does work.

### ISSUE THREAD

**Issue by mrmowgli** [rs459/bootstrap3-jade-sublime-plugin#15]
typing `bst` doesn't pop up the list of current available snippets.  However typing the full text (like bst-cdn) and tab to complete creates the snippet.  Just won't show the list of autocomplete snippets.

Sublime Stable channel,  3103 on Mac OSX Yosemite

Also, curious if there is a bootstrap4 version in the works?

**Comment by rs459** [comment]
Hi, 

It seems there an issue of sublime text 3103 itself. 

No changes was made since the release of 3103, inside this package.

[Jade language plugin](https://github.com/davidrios/jade-tmbundle) has changed, but is not the origin of the problem.

I'll continue to investigate.

---- 
About bootstrap 4, it's under development some changes can appear, for now, it's very close to bootstrap 3.
[Jade itself will be renamed as pug](https://github.com/pugjs/jade/issues/2184).

With all these information i think i will wait 'pug' and 'bootstrap 4' stable release.

**Comment by mrmowgli** [comment]
Hrmm now it's working again. Very strange.  I'll keep an eye out for when and why it happens.  Probably a bug with Sublime.

Thanks for the info about Pug, ugh what a pain trademarking common words can be.

**Comment by rs459** [comment]
It work's again for me,after reinstalling my package, it works also with dev 3105. 

I keep this issue open, i can't find where is the bug, i've made rollback with sublime text 3083 , with 3 previous version of jadetmplugin, and for all these test it doesn't work since i removed and installed again my package.
